server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telecom_campaign_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework: INFO

